import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#25252c",
        "on-tertiary-fixed-variant": "#6a006a",
        "secondary-container": "#006c50",
        "inverse-surface": "#fbf8ff",
        "on-primary": "#4a0076",
        tertiary: "#ff51fa",
        "surface-container": "#19191f",
        "secondary-dim": "#00edb4",
        "on-secondary-fixed": "#004734",
        "surface-container-low": "#131318",
        "tertiary-fixed": "#ff81f5",
        "secondary-fixed": "#00fdc1",
        "on-error": "#490013",
        "on-surface": "#f8f5fd",
        "on-primary-fixed-variant": "#470071",
        "surface-container-high": "#1f1f26",
        "inverse-on-surface": "#55545a",
        background: "#0e0e13",
        "on-tertiary-container": "#230023",
        primary: "#d394ff",
        secondary: "#00fdc1",
        "surface-dim": "#0e0e13",
        "surface-container-lowest": "#000000",
        "inverse-primary": "#9100e0",
        "primary-container": "#cb80ff",
        outline: "#76747b",
        "surface-container-highest": "#25252c",
        "on-background": "#f8f5fd",
        "tertiary-dim": "#ff51fa",
        "error-dim": "#d73357",
        "on-error-container": "#ffb2b9",
        "on-secondary": "#005c44",
        "on-tertiary-fixed": "#320032",
        error: "#ff6e84",
        "primary-fixed-dim": "#c26bff",
        "outline-variant": "#48474d",
        "tertiary-fixed-dim": "#ff61f8",
        "on-primary-container": "#39005c",
        "surface-tint": "#d394ff",
        surface: "#0e0e13",
        "on-surface-variant": "#acaab1",
        "error-container": "#a70138",
        "primary-fixed": "#cb80ff",
        "tertiary-container": "#fe00fe",
        "on-secondary-fixed-variant": "#00664c",
        "on-secondary-container": "#dfffef",
        "primary-dim": "#aa30fa",
        "on-primary-fixed": "#000000",
        "secondary-fixed-dim": "#00edb4",
        "on-tertiary": "#400040",
        "surface-bright": "#2c2b33",
      },
      fontFamily: {
        headline: ["'Space Grotesk'", "sans-serif"],
        body: ["'Manrope'", "sans-serif"],
        label: ["'Space Grotesk'", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1.5rem",
      },
      keyframes: {
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "slide-up": {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "feed-slide": {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "slide-up": "slide-up 0.6s ease-out forwards",
        "float": "float 6s ease-in-out infinite",
        "feed-slide": "feed-slide 0.5s ease-out forwards",
      },
    },
  },
  plugins: [],
};
export default config;
